//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4337
{
    using System;
    using System.Collections.Generic;
    using System.Data;

    public partial class Users
    {
        public string FullName { get; set; }
        public string ClientCode { get; set; }
        public DateTime DataBirth { get; set; }
        public string ClientIndex { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string House { get; set; }
        public string Flat { get; set; }
        public string Email { get; set; }
    }
}
