//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4337
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    
    public partial class Users2
    {
        [JsonPropertyName("Id")]
        public int IdClient { get; set; }
        public string FullName { get; set; }

        [JsonPropertyName("CodeClient")]
        public string ClientCode { get; set; }

        [JsonPropertyName("BirthDate")]
        [JsonConverter(typeof(Conveter))]
        public System.DateTime DataBirth { get; set; }

        [JsonPropertyName("Index")]
        public string ClientIndex { get; set; }
        public string City { get; set; }
        public string Street { get; set; }

        [JsonPropertyName("Home")]
        [JsonConverter(typeof(ConvertToInt))]
        public string House { get; set; }

        [JsonPropertyName("Kvartira")]
        [JsonConverter(typeof(ConvertToInt))]
        public string Flat { get; set; }

        [JsonPropertyName("E_mail")]
        public string Email { get; set; }
    }
}
